#
# Makefile for the sensors drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_CORE)		+= sensors_core.o
# accelerometer_sensor
obj-$(CONFIG_SENSORS_K2DH)		+= k2dh.o
# gyro_sensor
# combo chipset
# magnetic_sensor
obj-$(CONFIG_SENSORS_YAS532)	+= yas_mag_kernel_driver.o
obj-$(CONFIG_SENSORS_YAS_ORI)	+= yas_ori_kernel_driver.o
# optical_sensor
obj-$(CONFIG_SENSORS_BH1730)		+= bh1730.o
# barometer_sensor
# VE_GROUP
# grip sensor
obj-$(CONFIG_SENSORS_ASP01)     += asp01.o